# Generated by Django 5.2.1 on 2025-05-29 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('nama', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('no_identitas_klien', models.UUIDField()),
                ('tanggal_lahir', models.DateField()),
                ('url_foto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hewan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JenisHewan',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jenis_hewan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Klien',
            fields=[
                ('no_identitas', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal_registrasi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('kode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
                ('dosis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('no_pegawai', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tanggal_mulai_kerja', models.DateField()),
                ('tanggal_akhir_kerja', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perawatan',
            fields=[
                ('kode_perawatan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_perawatan', models.CharField(max_length=100)),
                ('biaya_perawatan', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('alamat', models.TextField()),
                ('nomor_telepon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vaksin',
            fields=[
                ('kode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('no_identitas_klien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petclinic.klien')),
                ('nama_depan', models.CharField(max_length=50)),
                ('nama_tengah', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_belakang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('no_identitas_klien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petclinic.klien')),
                ('nama_perusahaan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FrontDesk',
            fields=[
                ('no_front_desk', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='TenagaMedis',
            fields=[
                ('no_tenaga_medis', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_izin_praktik', models.CharField(max_length=50, unique=True)),
                ('no_pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='SertifikatKompetensi',
            fields=[
                ('no_sertifikat_kompetensi', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_sertifikat', models.CharField(max_length=100)),
                ('no_tenaga_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.tenagamedis')),
            ],
        ),
        migrations.CreateModel(
            name='PerawatHewan',
            fields=[
                ('no_perawat_hewan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_tenaga_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.tenagamedis')),
            ],
        ),
        migrations.CreateModel(
            name='DokterHewan',
            fields=[
                ('no_dokter_hewan', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_tenaga_medis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.tenagamedis')),
            ],
        ),
        migrations.AddField(
            model_name='pegawai',
            name='email_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.user'),
        ),
        migrations.AddField(
            model_name='klien',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.user'),
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id_kunjungan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipe_kunjungan', models.CharField(max_length=50)),
                ('timestamp_awal', models.DateTimeField()),
                ('timestamp_akhir', models.DateTimeField(blank=True, null=True)),
                ('suhu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('berat_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nama_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.hewan')),
                ('no_dokter_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.dokterhewan')),
                ('no_front_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.frontdesk')),
                ('no_identitas_klien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.klien')),
                ('no_perawat_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.perawathewan')),
                ('kode_vaksin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petclinic.vaksin')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPraktik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('jam', models.TimeField()),
                ('no_dokter_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.dokterhewan')),
            ],
            options={
                'unique_together': {('no_dokter_hewan', 'hari', 'jam')},
            },
        ),
        migrations.CreateModel(
            name='KunjunganKeperawatan',
            fields=[
                ('id_kunjungan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petclinic.kunjungan')),
                ('catatan', models.TextField()),
                ('kode_perawatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.perawatan')),
            ],
        ),
        migrations.CreateModel(
            name='PerawatanObat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas_obat', models.IntegerField()),
                ('kode_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.obat')),
                ('kode_perawatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petclinic.perawatan')),
            ],
            options={
                'unique_together': {('kode_perawatan', 'kode_obat')},
            },
        ),
    ]
