# Generated by Django 4.2.7 on 2025-06-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petclinic', '0008_add_triggers'),
        ('petclinic', 'triggers'),
    ]

    operations = [
    ]
