# Generated by Django 5.2.1 on 2025-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perawatan',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('biaya', models.IntegerField()),
            ],
        ),
    ]
