# Generated by Django 5.2.1 on 2025-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('dosis', models.TextField()),
            ],
        ),
    ]
