# Generated by Django 5.2.1 on 2025-05-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obat',
        ),
    ]
